### PR TITLE
Better status GUI

### PR DESCRIPTION
**Pull request by TheBigEye**
* Now it's not an ugly black bar anymore
* The arrows and durability counter are automatically adjusted to the status bar according to the size of the item name.
+ Added a function (drawCompleteBackground) to easily put transparent backgrounds to the text

This resolves https://github.com/chrisj42/minicraft-plus-revived/issues/204

### CODE REVIEW

**Review by Litorom — APPROVED** [review]
I have tested it. Works perfectly!

**Comment by Makkkkus** [comment]
Doesn't take into consideration longer names.

**Comment by Makkkkus** [comment]
It does look pretty nice though

**Comment by TheBigEye** [comment]
ok

**Comment by lino-levan** [comment]
Why was this closed?

**Comment by TheBigEye** [comment]
I dont know ._.

**Comment by BenCheung0422** [comment]
Can someone possible to provide a demo or screenshot about how it looks like?

**Comment by TheBigEye** [comment]
> Can someone possible to provide a demo or screenshot about how it looks like?

image
* It has an icon and next to it the name of the item

The problem is the long names, this is because the resolution of the game/window is very low, @pelletsstarPL had recommended that the names do a kind of horizontal scroll in order to compensate for that, but I left it there

**Comment by BenCheung0422** [comment]
It seems like the design of it can still be improved. I may add new textures while updating this.

**Comment by BenCheung0422** [comment]
I am curious, what was it at the bottom right corner?

**Comment by BenCheung0422** [comment]
I have deeply (quite) search about that. That was armor, but the position of armor points changed later (5d7304ffd86cfd236804d5e72ee0edd1a0de0e99).

**Pull request closed without merging**
