### PR TITLE
Changes and corrections

### PR DESCRIPTION
**Pull request by TheBigEye**
- ~~Cleaned InputHandler.java, Settings.java, ConsoleReader.java, Sound.java and Localization.java~~
- Fixed a typing error in LevelGen.java
- Now JSON files are indented on save (which improves the readability of the files for the user)
- The game can now save and load the difficulty

### CODE REVIEW

**Comment by lino-levan** [comment]
GGs for this because when I was messing with he input handler it was only trouble. Props for cleaning up the code.

**Comment by Makkkkus** [comment]
Please revert the cleaning stuff. It is confusing to look at, and it makes compact code less readable.

**Comment by TheBigEye** [comment]
ok

**Comment by Makkkkus** [comment]
Thank you very much!

**Comment by Makkkkus** [comment]
EXCELLENT!!!

**Pull request merged**
