### PR TITLE
Russian localization... Doesn't work

### PR DESCRIPTION
**Pull request by TerisbackDev**
I recently met this game, and I want to make a translation into my own language.
But how to do that?

### CODE REVIEW

**Comment by chrisj42** [comment]
so you had a lot of weird control characters in Font.java...
screenshot

...but I think I fixed it...

**Comment by TerisbackDev** [comment]
I'm working on the correct output ...

**Comment by chrisj42** [comment]
Oh wow, they were in russian.mcpl too
controlchars

**Comment by chrisj42** [comment]
uhh... I fixed it..?
menu

I just need to figure out how Font.java determines when to break the line in the main character string

**Comment by chrisj42** [comment]
something to do with this...
fontpos

**Comment by chrisj42** [comment]
So I've done some debugging... and I think a found a source of error... Unicode or whatever treats russian characters special, or something... it seems that your characters are made up of a bunch of other characters, because when it parses the stuff from the localization file, it's finding characters that I don't see in there:

`drawing char at pos 2 from spritesheet; should be "C"
drawing char at pos 7 from spritesheet; should be "H"
drawing char at pos 4 from spritesheet; should be "E"
drawing char at pos 10 from spritesheet; should be "K"
drawing char at pos 8 from spritesheet; should be "I"
drawing char at pos 13 from spritesheet; should be "N"
drawing char at pos 6 from spritesheet; should be "G"
could not find char " " (32) in font string.
drawing char at pos 5 from spritesheet; should be "F"
drawing char at pos 14 from spritesheet; should be "O"
drawing char at pos 17 from spritesheet; should be "R"
drawing char at pos 20 from spritesheet; should be "U"
drawing char at pos 15 from spritesheet; should be "P"
drawing char at pos 3 from spritesheet; should be "D"
drawing char at pos 0 from spritesheet; should be "A"
drawing char at pos 19 from spritesheet; should be "T"
drawing char at pos 18 from spritesheet; should be "S"
drawing char at pos 42 from spritesheet; should be "."
could not find char "Ð" (208) in font string.
could not find char "" (152) in font string.
could not find char "³" (179) in font string.
could not find char "Ñ" (209) in font string.
could not find char "" (128) in font string.
could not find char "°" (176) in font string.
could not find char "" (130) in font string.
could not find char "" (140) in font string.
drawing char at pos 57 from spritesheet; should be ">"
drawing char at pos 56 from spritesheet; should be "<"
could not find char "" (159) in font string.
could not find char "¸" (184) in font string.
could not find char "" (129) in font string.
could not find char "¾" (190) in font string.
could not find char "Μ" (924) in font string.
could not find char "´" (180) in font string.
could not find char "½" (189) in font string.
could not find char "" (143) in font string.
could not find char "º" (186) in font string.
could not find char "¼" (188) in font string.
could not find char "" (131) in font string.
could not find char "" (157) in font string.
could not find char "¹" (185) in font string.
could not find char "" (137) in font string.
could not find char "" (146) in font string.
could not find char "" (139) in font string.
drawing char at pos 12 from spritesheet; should be "M"
drawing char at pos 44 from spritesheet; should be "!"
drawing char at pos 21 from spritesheet; should be "V"
drawing char at pos 34 from spritesheet; should be "2"
drawing char at pos 32 from spritesheet; should be "0"
drawing char at pos 36 from spritesheet; should be "4"
drawing char at pos 54 from spritesheet; should be "("
drawing char at pos 43 from spritesheet; should be ","
drawing char at pos 22 from spritesheet; should be "W"
could not find char "»" (187) in font string.
could not find char "²" (178) in font string.
could not find char "±" (177) in font string.
drawing char at pos 55 from spritesheet; should be ")"
could not find char "¿" (191) in font string.
drawing char at pos 11 from spritesheet; should be "L"
latest version = 2.0.4
drawing char at pos 24 from spritesheet; should be "Y"`

**Comment by TerisbackDev** [comment]
I know, I want to implement the work with "UTF-8"

**Comment by TerisbackDev** [comment]
Therefore, I closed the request. I want to think about it, and maybe I will solve it.

**Comment by chrisj42** [comment]
I'm not sure how to iterate over russian characters in a way that goes one full russian character at a time, though; currently, it just uses `string.length()` and `string.charAt(idx)`.

**Comment by TerisbackDev** [comment]
¯\_(ツ)_/¯
I will solve this problem. Simply, do not touch.

**Comment by TerisbackDev** [comment]
I'll write in a discord when I do this

**Comment by chrisj42** [comment]
lol alright then. I will let you do your thing.

**Pull request closed without merging**
