### PR TITLE
Made some small changes

### PR DESCRIPTION
**Pull request by africalinguist**

### CODE REVIEW

**Comment by chrisj42** [comment]
wait, why did you change the indexing of the random splash? Isn't it never going to choose the first one anymore?

**Comment by MaxACartwright** [comment]
v

**Comment by africalinguist** [comment]
It's so that the splashes for certain dates will never be picked if it's not that date

**Comment by chrisj42** [comment]
ah I see, it didn't seem that way in the splashes commit, but I see now.

**Pull request merged**
