### PR TITLE
Airwizard Loading Level Fix

### PR DESCRIPTION
**Pull request by lino-levan**
Fixes issue listed [here](https://github.com/chrisj42/minicraft-plus-revived/issues/217).

It was purely a loading bug.

### CODE REVIEW

**Comment by Makkkkus** [comment]
image

This scares me. Please fix.

**Comment by lino-levan** [comment]
This is due to whitespace/newline changes due to IDE auto formatting. 

"Empty file" essentially means "No changes".

The file is in fact identical to the gradlew file already in the current directory if you look at the repo.

To be honest I'm not exactly sure how to "unpush" a file from a repo but if you're still scared I can look into it.

**Comment by Makkkkus** [comment]
> To be honest I'm not exactly sure how to "unpush" a file from a repo but if you're still scared I can look into it.

git reset --soft HEAD~1

Then commit the changes again

**Comment by Litorom** [comment]
What is the issue that being fixed here?

**Comment by lino-levan** [comment]
Fixed

**Pull request merged**
